version: 2
jobs:
  test_python35:
    docker:
      - image: circleci/python:3.5.5

    steps:
      - checkout

      # install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test
            make e2e_test