version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15-stretch
      - image: circleci/python:3.4.8-jessie-node
      - image: circleci/python:3.5.5-jessie
      - image: circleci/python:3.6.5-jessie

    steps:
      - checkout
      - run: # install dependencies
          name: install dependencies
          command: |
            pip install --user .
      - run: # run tests!
          name: run tests
          command: |
            make test
            make e2e_test